version: '1'

services:
  finance-api:
    platform: linux/amd64
    build:
      context: ./
      dockerfile: ./Dockerfile
    ports:
      - '4100:4100'
    volumes:
      - ./:/usr/api
      - ./logs/:/usr/api/logs 